apiVersion: v1
kind: Secret
metadata:
  name: forum-postgres-db-credentials
type: Opaque
data:
  host: Zm9ydW0tcG9zdGdyZXMtc2VydmljZQ== # gm-postgres-service
  db: NHVt
  user: NHVtdXNlcg==
  password: NHVtcGFzc3dvcmQ=
